class FlowerExecutor {

    public static void main(String[] args) {

        System.out.println("---------------------------");

        Flower f1 = new Flower();

        f1.name = "Rose";
        f1.color = "Red";
        f1.fragrance = "Strong";
        f1.numberOfPetals = 32;
        f1.isSeasonal = false;
        f1.price = 20;
        f1.countryOfOrigin = "India";

        System.out.println("Name: " + f1.name);
        System.out.println("Color: " + f1.color);
        System.out.println("Fragrance: " + f1.fragrance);
        System.out.println("Number of Petals: " + f1.numberOfPetals);
        System.out.println("Is Seasonal: " + f1.isSeasonal);
        System.out.println("Price: " + f1.price);
        System.out.println("Country of Origin: " + f1.countryOfOrigin);


        System.out.println("---------------------------");

        Flower f2 = new Flower();

        f2.name = "Lotus";
        f2.color = "Pink";
        f2.fragrance = "Mild";
        f2.numberOfPetals = 24;
        f2.isSeasonal = true;
        f2.price = 30;
        f2.countryOfOrigin = "India";

        System.out.println("Name: " + f2.name);
        System.out.println("Color: " + f2.color);
        System.out.println("Fragrance: " + f2.fragrance);
        System.out.println("Number of Petals: " + f2.numberOfPetals);
        System.out.println("Is Seasonal: " + f2.isSeasonal);
        System.out.println("Price: " + f2.price);
        System.out.println("Country of Origin: " + f2.countryOfOrigin);

        Flower f3 = new Flower();
        f3.name = "Sunflower";
        f3.color = "Yellow";
        f3.fragrance = "Mild";
        f3.numberOfPetals = 34;
        f3.isSeasonal = true;
        f3.price = 15;
        f3.countryOfOrigin = "USA";
        System.out.println("---------------------------");
        System.out.println("Name: " + f3.name);
        System.out.println("Color: " + f3.color);
        System.out.println("Fragrance: " + f3.fragrance);
        System.out.println("Number of Petals: " + f3.numberOfPetals);
        System.out.println("Is Seasonal: " + f3.isSeasonal);
        System.out.println("Price: " + f3.price);
        System.out.println("Country of Origin: " + f3.countryOfOrigin);

        Flower f4 = new Flower();
        f4.name = "Lily";
        f4.color = "White";
        f4.fragrance = "Strong";
        f4.numberOfPetals = 6;
        f4.isSeasonal = false;
        f4.price = 25;
        f4.countryOfOrigin = "India";
        System.out.println("---------------------------");
        System.out.println("Name: " + f4.name);
        System.out.println("Color: " + f4.color);
        System.out.println("Fragrance: " + f4.fragrance);
        System.out.println("Number of Petals: " + f4.numberOfPetals);
        System.out.println("Is Seasonal: " + f4.isSeasonal);
        System.out.println("Price: " + f4.price);
        System.out.println("Country of Origin: " + f4.countryOfOrigin);

        Flower f5 = new Flower();
        f5.name = "Tulip";
        f5.color = "Red";
        f5.fragrance = "Mild";
        f5.numberOfPetals = 6;
        f5.isSeasonal = true;
        f5.price = 40;
        f5.countryOfOrigin = "Netherlands";
        System.out.println("---------------------------");
        System.out.println("Name: " + f5.name);
        System.out.println("Color: " + f5.color);
        System.out.println("Fragrance: " + f5.fragrance);
        System.out.println("Number of Petals: " + f5.numberOfPetals);
        System.out.println("Is Seasonal: " + f5.isSeasonal);
        System.out.println("Price: " + f5.price);
        System.out.println("Country of Origin: " + f5.countryOfOrigin);

        Flower f6 = new Flower();
        f6.name = "Jasmine";
        f6.color = "White";
        f6.fragrance = "Strong";
        f6.numberOfPetals = 5;
        f6.isSeasonal = false;
        f6.price = 10;
        f6.countryOfOrigin = "India";
        System.out.println("---------------------------");
        System.out.println("Name: " + f6.name);
        System.out.println("Color: " + f6.color);
        System.out.println("Fragrance: " + f6.fragrance);
        System.out.println("Number of Petals: " + f6.numberOfPetals);
        System.out.println("Is Seasonal: " + f6.isSeasonal);
        System.out.println("Price: " + f6.price);
        System.out.println("Country of Origin: " + f6.countryOfOrigin);

        Flower f7 = new Flower();
        f7.name = "Orchid";
        f7.color = "Purple";
        f7.fragrance = "Mild";
        f7.numberOfPetals = 5;
        f7.isSeasonal = false;
        f7.price = 50;
        f7.countryOfOrigin = "Thailand";
        System.out.println("---------------------------");
        System.out.println("Name: " + f7.name);
        System.out.println("Color: " + f7.color);
        System.out.println("Fragrance: " + f7.fragrance);
        System.out.println("Number of Petals: " + f7.numberOfPetals);
        System.out.println("Is Seasonal: " + f7.isSeasonal);
        System.out.println("Price: " + f7.price);
        System.out.println("Country of Origin: " + f7.countryOfOrigin);

        Flower f8 = new Flower();
        f8.name = "Marigold";
        f8.color = "Orange";
        f8.fragrance = "Strong";
        f8.numberOfPetals = 30;
        f8.isSeasonal = true;
        f8.price = 8;
        f8.countryOfOrigin = "India";
        System.out.println("---------------------------");
        System.out.println("Name: " + f8.name);
        System.out.println("Color: " + f8.color);
        System.out.println("Fragrance: " + f8.fragrance);
        System.out.println("Number of Petals: " + f8.numberOfPetals);
        System.out.println("Is Seasonal: " + f8.isSeasonal);
        System.out.println("Price: " + f8.price);
        System.out.println("Country of Origin: " + f8.countryOfOrigin);

        Flower f9 = new Flower();
        f9.name = "Daisy";
        f9.color = "White";
        f9.fragrance = "Mild";
        f9.numberOfPetals = 20;
        f9.isSeasonal = true;
        f9.price = 12;
        f9.countryOfOrigin = "USA";
        System.out.println("---------------------------");
        System.out.println("Name: " + f9.name);
        System.out.println("Color: " + f9.color);
        System.out.println("Fragrance: " + f9.fragrance);
        System.out.println("Number of Petals: " + f9.numberOfPetals);
        System.out.println("Is Seasonal: " + f9.isSeasonal);
        System.out.println("Price: " + f9.price);
        System.out.println("Country of Origin: " + f9.countryOfOrigin);

        Flower f10 = new Flower();
        f10.name = "Lavender";
        f10.color = "Purple";
        f10.fragrance = "Strong";
        f10.numberOfPetals = 15;
        f10.isSeasonal = false;
        f10.price = 35;
        f10.countryOfOrigin = "France";
        System.out.println("---------------------------");
        System.out.println("Name: " + f10.name);
        System.out.println("Color: " + f10.color);
        System.out.println("Fragrance: " + f10.fragrance);
        System.out.println("Number of Petals: " + f10.numberOfPetals);
        System.out.println("Is Seasonal: " + f10.isSeasonal);
        System.out.println("Price: " + f10.price);
        System.out.println("Country of Origin: " + f10.countryOfOrigin);

        Flower f11 = new Flower();
        f11.name = "Hibiscus";
        f11.color = "Red";
        f11.fragrance = "Mild";
        f11.numberOfPetals = 5;
        f11.isSeasonal = true;
        f11.price = 10;
        f11.countryOfOrigin = "India";
        System.out.println("---------------------------");
        System.out.println("Name: " + f11.name);
        System.out.println("Color: " + f11.color);
        System.out.println("Fragrance: " + f11.fragrance);
        System.out.println("Number of Petals: " + f11.numberOfPetals);
        System.out.println("Is Seasonal: " + f11.isSeasonal);
        System.out.println("Price: " + f11.price);
        System.out.println("Country of Origin: " + f11.countryOfOrigin);

        Flower f12 = new Flower();
        f12.name = "Peony";
        f12.color = "Pink";
        f12.fragrance = "Strong";
        f12.numberOfPetals = 25;
        f12.isSeasonal = true;
        f12.price = 60;
        f12.countryOfOrigin = "China";
        System.out.println("---------------------------");
        System.out.println("Name: " + f12.name);
        System.out.println("Color: " + f12.color);
        System.out.println("Fragrance: " + f12.fragrance);
        System.out.println("Number of Petals: " + f12.numberOfPetals);
        System.out.println("Is Seasonal: " + f12.isSeasonal);
        System.out.println("Price: " + f12.price);
        System.out.println("Country of Origin: " + f12.countryOfOrigin);

        Flower f13 = new Flower();
        f13.name = "Chrysanthemum";
        f13.color = "Yellow";
        f13.fragrance = "Mild";
        f13.numberOfPetals = 40;
        f13.isSeasonal = true;
        f13.price = 18;
        f13.countryOfOrigin = "Japan";
        System.out.println("---------------------------");
        System.out.println("Name: " + f13.name);
        System.out.println("Color: " + f13.color);
        System.out.println("Fragrance: " + f13.fragrance);
        System.out.println("Number of Petals: " + f13.numberOfPetals);
        System.out.println("Is Seasonal: " + f13.isSeasonal);
        System.out.println("Price: " + f13.price);
        System.out.println("Country of Origin: " + f13.countryOfOrigin);

        Flower f14 = new Flower();
        f14.name = "Magnolia";
        f14.color = "White";
        f14.fragrance = "Strong";
        f14.numberOfPetals = 10;
        f14.isSeasonal = false;
        f14.price = 45;
        f14.countryOfOrigin = "USA";
        System.out.println("---------------------------");
        System.out.println("Name: " + f14.name);
        System.out.println("Color: " + f14.color);
        System.out.println("Fragrance: " + f14.fragrance);
        System.out.println("Number of Petals: " + f14.numberOfPetals);
        System.out.println("Is Seasonal: " + f14.isSeasonal);
        System.out.println("Price: " + f14.price);
        System.out.println("Country of Origin: " + f14.countryOfOrigin);

        Flower f15 = new Flower();
        f15.name = "Gardenia";
        f15.color = "White";
        f15.fragrance = "Strong";
        f15.numberOfPetals = 12;
        f15.isSeasonal = false;
        f15.price = 30;
        f15.countryOfOrigin = "China";
        System.out.println("---------------------------");
        System.out.println("Name: " + f15.name);
        System.out.println("Color: " + f15.color);
        System.out.println("Fragrance: " + f15.fragrance);
        System.out.println("Number of Petals: " + f15.numberOfPetals);
        System.out.println("Is Seasonal: " + f15.isSeasonal);
        System.out.println("Price: " + f15.price);
        System.out.println("Country of Origin: " + f15.countryOfOrigin);

        Flower f16 = new Flower();
        f16.name = "Carnation";
        f16.color = "Pink";
        f16.fragrance = "Mild";
        f16.numberOfPetals = 20;
        f16.isSeasonal = true;
        f16.price = 15;
        f16.countryOfOrigin = "Italy";
        System.out.println("---------------------------");
        System.out.println("Name: " + f16.name);
        System.out.println("Color: " + f16.color);
        System.out.println("Fragrance: " + f16.fragrance);
        System.out.println("Number of Petals: " + f16.numberOfPetals);
        System.out.println("Is Seasonal: " + f16.isSeasonal);
        System.out.println("Price: " + f16.price);
        System.out.println("Country of Origin: " + f16.countryOfOrigin);

        Flower f17 = new Flower();
        f17.name = "Zinnia";
        f17.color = "Red";
        f17.fragrance = "Mild";
        f17.numberOfPetals = 18;
        f17.isSeasonal = true;
        f17.price = 10;
        f17.countryOfOrigin = "Mexico";
        System.out.println("---------------------------");
        System.out.println("Name: " + f17.name);
        System.out.println("Color: " + f17.color);
        System.out.println("Fragrance: " + f17.fragrance);
        System.out.println("Number of Petals: " + f17.numberOfPetals);
        System.out.println("Is Seasonal: " + f17.isSeasonal);
        System.out.println("Price: " + f17.price);
        System.out.println("Country of Origin: " + f17.countryOfOrigin);

        Flower f18 = new Flower();
        f18.name = "Aster";
        f18.color = "Purple";
        f18.fragrance = "Mild";
        f18.numberOfPetals = 22;
        f18.isSeasonal = true;
        f18.price = 14;
        f18.countryOfOrigin = "Greece";
        System.out.println("---------------------------");
        System.out.println("Name: " + f18.name);
        System.out.println("Color: " + f18.color);
        System.out.println("Fragrance: " + f18.fragrance);
        System.out.println("Number of Petals: " + f18.numberOfPetals);
        System.out.println("Is Seasonal: " + f18.isSeasonal);
        System.out.println("Price: " + f18.price);
        System.out.println("Country of Origin: " + f18.countryOfOrigin);

        Flower f19 = new Flower();
        f19.name = "Bluebell";
        f19.color = "Blue";
        f19.fragrance = "Mild";
        f19.numberOfPetals = 6;
        f19.isSeasonal = true;
        f19.price = 16;
        f19.countryOfOrigin = "UK";
        System.out.println("---------------------------");
        System.out.println("Name: " + f19.name);
        System.out.println("Color: " + f19.color);
        System.out.println("Fragrance: " + f19.fragrance);
        System.out.println("Number of Petals: " + f19.numberOfPetals);
        System.out.println("Is Seasonal: " + f19.isSeasonal);
        System.out.println("Price: " + f19.price);
        System.out.println("Country of Origin: " + f19.countryOfOrigin);

        Flower f20 = new Flower();
        f20.name = "Begonia";
        f20.color = "Pink";
        f20.fragrance = "Mild";
        f20.numberOfPetals = 10;
        f20.isSeasonal = true;
        f20.price = 12;
        f20.countryOfOrigin = "Brazil";
        System.out.println("---------------------------");
        System.out.println("Name: " + f20.name);
        System.out.println("Color: " + f20.color);
        System.out.println("Fragrance: " + f20.fragrance);
        System.out.println("Number of Petals: " + f20.numberOfPetals);
        System.out.println("Is Seasonal: " + f20.isSeasonal);
        System.out.println("Price: " + f20.price);
        System.out.println("Country of Origin: " + f20.countryOfOrigin);

        Flower f21 = new Flower();
        f21.name = "Camellia";
        f21.color = "White";
        f21.fragrance = "Mild";
        f21.numberOfPetals = 15;
        f21.isSeasonal = false;
        f21.price = 25;
        f21.countryOfOrigin = "Japan";
        System.out.println("---------------------------");
        System.out.println("Name: " + f21.name);
        System.out.println("Color: " + f21.color);
        System.out.println("Fragrance: " + f21.fragrance);
        System.out.println("Number of Petals: " + f21.numberOfPetals);
        System.out.println("Is Seasonal: " + f21.isSeasonal);
        System.out.println("Price: " + f21.price);
        System.out.println("Country of Origin: " + f21.countryOfOrigin);

        Flower f22 = new Flower();
        f22.name = "Daffodil";
        f22.color = "Yellow";
        f22.fragrance = "Mild";
        f22.numberOfPetals = 6;
        f22.isSeasonal = true;
        f22.price = 18;
        f22.countryOfOrigin = "Wales";
        System.out.println("---------------------------");
        System.out.println("Name: " + f22.name);
        System.out.println("Color: " + f22.color);
        System.out.println("Fragrance: " + f22.fragrance);
        System.out.println("Number of Petals: " + f22.numberOfPetals);
        System.out.println("Is Seasonal: " + f22.isSeasonal);
        System.out.println("Price: " + f22.price);
        System.out.println("Country of Origin: " + f22.countryOfOrigin);

        Flower f23 = new Flower();
        f23.name = "Freesia";
        f23.color = "White";
        f23.fragrance = "Strong";
        f23.numberOfPetals = 6;
        f23.isSeasonal = true;
        f23.price = 22;
        f23.countryOfOrigin = "South Africa";
        System.out.println("---------------------------");
        System.out.println("Name: " + f23.name);
        System.out.println("Color: " + f23.color);
        System.out.println("Fragrance: " + f23.fragrance);
        System.out.println("Number of Petals: " + f23.numberOfPetals);
        System.out.println("Is Seasonal: " + f23.isSeasonal);
        System.out.println("Price: " + f23.price);
        System.out.println("Country of Origin: " + f23.countryOfOrigin);

        Flower f24 = new Flower();
        f24.name = "Geranium";
        f24.color = "Red";
        f24.fragrance = "Mild";
        f24.numberOfPetals = 5;
        f24.isSeasonal = false;
        f24.price = 14;
        f24.countryOfOrigin = "South Africa";
        System.out.println("---------------------------");
        System.out.println("Name: " + f24.name);
        System.out.println("Color: " + f24.color);
        System.out.println("Fragrance: " + f24.fragrance);
        System.out.println("Number of Petals: " + f24.numberOfPetals);
        System.out.println("Is Seasonal: " + f24.isSeasonal);
        System.out.println("Price: " + f24.price);
        System.out.println("Country of Origin: " + f24.countryOfOrigin);

        Flower f25 = new Flower();
        f25.name = "Heliconia";
        f25.color = "Orange";
        f25.fragrance = "Mild";
        f25.numberOfPetals = 8;
        f25.isSeasonal = true;
        f25.price = 35;
        f25.countryOfOrigin = "Colombia";
        System.out.println("---------------------------");
        System.out.println("Name: " + f25.name);
        System.out.println("Color: " + f25.color);
        System.out.println("Fragrance: " + f25.fragrance);
        System.out.println("Number of Petals: " + f25.numberOfPetals);
        System.out.println("Is Seasonal: " + f25.isSeasonal);
        System.out.println("Price: " + f25.price);
        System.out.println("Country of Origin: " + f25.countryOfOrigin);

        Flower f26 = new Flower();
        f26.name = "Iris";
        f26.color = "Purple";
        f26.fragrance = "Mild";
        f26.numberOfPetals = 6;
        f26.isSeasonal = true;
        f26.price = 20;
        f26.countryOfOrigin = "France";
        System.out.println("---------------------------");
        System.out.println("Name: " + f26.name);
        System.out.println("Color: " + f26.color);
        System.out.println("Fragrance: " + f26.fragrance);
        System.out.println("Number of Petals: " + f26.numberOfPetals);
        System.out.println("Is Seasonal: " + f26.isSeasonal);
        System.out.println("Price: " + f26.price);
        System.out.println("Country of Origin: " + f26.countryOfOrigin);

        Flower f27 = new Flower();
        f27.name = "Ixora";
        f27.color = "Red";
        f27.fragrance = "Mild";
        f27.numberOfPetals = 4;
        f27.isSeasonal = false;
        f27.price = 10;
        f27.countryOfOrigin = "India";
        System.out.println("---------------------------");
        System.out.println("Name: " + f27.name);
        System.out.println("Color: " + f27.color);
        System.out.println("Fragrance: " + f27.fragrance);
        System.out.println("Number of Petals: " + f27.numberOfPetals);
        System.out.println("Is Seasonal: " + f27.isSeasonal);
        System.out.println("Price: " + f27.price);
        System.out.println("Country of Origin: " + f27.countryOfOrigin);

        Flower f28 = new Flower();
        f28.name = "Kalanchoe";
        f28.color = "Pink";
        f28.fragrance = "Mild";
        f28.numberOfPetals = 4;
        f28.isSeasonal = false;
        f28.price = 18;
        f28.countryOfOrigin = "Madagascar";
        System.out.println("---------------------------");
        System.out.println("Name: " + f28.name);
        System.out.println("Color: " + f28.color);
        System.out.println("Fragrance: " + f28.fragrance);
        System.out.println("Number of Petals: " + f28.numberOfPetals);
        System.out.println("Is Seasonal: " + f28.isSeasonal);
        System.out.println("Price: " + f28.price);
        System.out.println("Country of Origin: " + f28.countryOfOrigin);

        Flower f29 = new Flower();
        f29.name = "Lantana";
        f29.color = "Orange";
        f29.fragrance = "Mild";
        f29.numberOfPetals = 5;
        f29.isSeasonal = true;
        f29.price = 12;
        f29.countryOfOrigin = "America";
        System.out.println("---------------------------");
        System.out.println("Name: " + f29.name);
        System.out.println("Color: " + f29.color);
        System.out.println("Fragrance: " + f29.fragrance);
        System.out.println("Number of Petals: " + f29.numberOfPetals);
        System.out.println("Is Seasonal: " + f29.isSeasonal);
        System.out.println("Price: " + f29.price);
        System.out.println("Country of Origin: " + f29.countryOfOrigin);

        Flower f30 = new Flower();
        f30.name = "Narcissus";
        f30.color = "Yellow";
        f30.fragrance = "Strong";
        f30.numberOfPetals = 6;
        f30.isSeasonal = true;
        f30.price = 20;
        f30.countryOfOrigin = "Europe";
        System.out.println("---------------------------");
        System.out.println("Name: " + f30.name);
        System.out.println("Color: " + f30.color);
        System.out.println("Fragrance: " + f30.fragrance);
        System.out.println("Number of Petals: " + f30.numberOfPetals);
        System.out.println("Is Seasonal: " + f30.isSeasonal);
        System.out.println("Price: " + f30.price);
        System.out.println("Country of Origin: " + f30.countryOfOrigin);
    }
}

