class MedicineRunner {

    public static void main(String[] medicine) {

        Medicine m1 = new Medicine();

        m1.name = "Dolo";
        m1.brand = "Crocin";
        m1.type = "Tablet";
        m1.dosageMg = 500;
        m1.isPrescriptionRequired = false;
        m1.price = 30;
        m1.expiryDate = "12/2026";

        System.out.println("Name: " + m1.name);
        System.out.println("Brand: " + m1.brand);
        System.out.println("Type: " + m1.type);
        System.out.println("Dosage: " + m1.dosageMg + "mg");
        System.out.println("Prescription Required: " + m1.isPrescriptionRequired);
        System.out.println("Price: " + m1.price);
        System.out.println("Expiry Date: " + m1.expiryDate);


        System.out.println("---------------------------");

        Medicine m2 = new Medicine();

        m2.name = "Ibuprofen";
        m2.brand = "Brufen";
        m2.type = "Tablet";
        m2.dosageMg = 400;
        m2.isPrescriptionRequired = false;
        m2.price = 50;
        m2.expiryDate = "08/2026";

        System.out.println("Name: " + m2.name);
        System.out.println("Brand: " + m2.brand);
        System.out.println("Type: " + m2.type);
        System.out.println("Dosage: " + m2.dosageMg + "mg");
        System.out.println("Prescription Required: " + m2.isPrescriptionRequired);
        System.out.println("Price: " + m2.price);
        System.out.println("Expiry Date: " + m2.expiryDate);

        Medicine m3 = new Medicine();
        m3.name = "Amoxicillin";
        m3.brand = "Mox";
        m3.type = "Capsule";
        m3.dosageMg = 500;
        m3.isPrescriptionRequired = true;
        m3.price = 120;
        m3.expiryDate = "10/2026";
        System.out.println("---------------------------");
        System.out.println("Name: " + m3.name);
        System.out.println("Brand: " + m3.brand);
        System.out.println("Type: " + m3.type);
        System.out.println("Dosage: " + m3.dosageMg + "mg");
        System.out.println("Prescription Required: " + m3.isPrescriptionRequired);
        System.out.println("Price: " + m3.price);
        System.out.println("Expiry Date: " + m3.expiryDate);

        Medicine m4 = new Medicine();
        m4.name = "Cetirizine";
        m4.brand = "Cetzine";
        m4.type = "Tablet";
        m4.dosageMg = 10;
        m4.isPrescriptionRequired = false;
        m4.price = 20;
        m4.expiryDate = "05/2027";
        System.out.println("---------------------------");
        System.out.println("Name: " + m4.name);
        System.out.println("Brand: " + m4.brand);
        System.out.println("Type: " + m4.type);
        System.out.println("Dosage: " + m4.dosageMg + "mg");
        System.out.println("Prescription Required: " + m4.isPrescriptionRequired);
        System.out.println("Price: " + m4.price);
        System.out.println("Expiry Date: " + m4.expiryDate);

        Medicine m5 = new Medicine();
        m5.name = "Azithromycin";
        m5.brand = "Azee";
        m5.type = "Tablet";
        m5.dosageMg = 500;
        m5.isPrescriptionRequired = true;
        m5.price = 150;
        m5.expiryDate = "09/2026";
        System.out.println("---------------------------");
        System.out.println("Name: " + m5.name);
        System.out.println("Brand: " + m5.brand);
        System.out.println("Type: " + m5.type);
        System.out.println("Dosage: " + m5.dosageMg + "mg");
        System.out.println("Prescription Required: " + m5.isPrescriptionRequired);
        System.out.println("Price: " + m5.price);
        System.out.println("Expiry Date: " + m5.expiryDate);

        Medicine m6 = new Medicine();
        m6.name = "Paracetamol";
        m6.brand = "Dolo650";
        m6.type = "Tablet";
        m6.dosageMg = 650;
        m6.isPrescriptionRequired = false;
        m6.price = 35;
        m6.expiryDate = "11/2026";
        System.out.println("---------------------------");
        System.out.println("Name: " + m6.name);
        System.out.println("Brand: " + m6.brand);
        System.out.println("Type: " + m6.type);
        System.out.println("Dosage: " + m6.dosageMg + "mg");
        System.out.println("Prescription Required: " + m6.isPrescriptionRequired);
        System.out.println("Price: " + m6.price);
        System.out.println("Expiry Date: " + m6.expiryDate);

        Medicine m7 = new Medicine();
        m7.name = "Pantoprazole";
        m7.brand = "Pantocid";
        m7.type = "Tablet";
        m7.dosageMg = 40;
        m7.isPrescriptionRequired = true;
        m7.price = 90;
        m7.expiryDate = "07/2026";
        System.out.println("---------------------------");
        System.out.println("Name: " + m7.name);
        System.out.println("Brand: " + m7.brand);
        System.out.println("Type: " + m7.type);
        System.out.println("Dosage: " + m7.dosageMg + "mg");
        System.out.println("Prescription Required: " + m7.isPrescriptionRequired);
        System.out.println("Price: " + m7.price);
        System.out.println("Expiry Date: " + m7.expiryDate);

        Medicine m8 = new Medicine();
        m8.name = "Metformin";
        m8.brand = "Glycomet";
        m8.type = "Tablet";
        m8.dosageMg = 500;
        m8.isPrescriptionRequired = true;
        m8.price = 80;
        m8.expiryDate = "12/2026";
        System.out.println("---------------------------");
        System.out.println("Name: " + m8.name);
        System.out.println("Brand: " + m8.brand);
        System.out.println("Type: " + m8.type);
        System.out.println("Dosage: " + m8.dosageMg + "mg");
        System.out.println("Prescription Required: " + m8.isPrescriptionRequired);
        System.out.println("Price: " + m8.price);
        System.out.println("Expiry Date: " + m8.expiryDate);

        Medicine m9 = new Medicine();
        m9.name = "ORS";
        m9.brand = "Electral";
        m9.type = "Powder";
        m9.dosageMg = 0;
        m9.isPrescriptionRequired = false;
        m9.price = 25;
        m9.expiryDate = "03/2027";
        System.out.println("---------------------------");
        System.out.println("Name: " + m9.name);
        System.out.println("Brand: " + m9.brand);
        System.out.println("Type: " + m9.type);
        System.out.println("Dosage: " + m9.dosageMg + "mg");
        System.out.println("Prescription Required: " + m9.isPrescriptionRequired);
        System.out.println("Price: " + m9.price);
        System.out.println("Expiry Date: " + m9.expiryDate);

        Medicine m10 = new Medicine();
        m10.name = "Cough Syrup";
        m10.brand = "Benadryl";
        m10.type = "Syrup";
        m10.dosageMg = 0;
        m10.isPrescriptionRequired = false;
        m10.price = 110;
        m10.expiryDate = "01/2027";
        System.out.println("---------------------------");
        System.out.println("Name: " + m10.name);
        System.out.println("Brand: " + m10.brand);
        System.out.println("Type: " + m10.type);
        System.out.println("Dosage: " + m10.dosageMg + "mg");
        System.out.println("Prescription Required: " + m10.isPrescriptionRequired);
        System.out.println("Price: " + m10.price);
        System.out.println("Expiry Date: " + m10.expiryDate);

        Medicine m11 = new Medicine();
        m11.name = "Vitamin C";
        m11.brand = "Limcee";
        m11.type = "Tablet";
        m11.dosageMg = 500;
        m11.isPrescriptionRequired = false;
        m11.price = 60;
        m11.expiryDate = "06/2027";
        System.out.println("---------------------------");
        System.out.println("Name: " + m11.name);
        System.out.println("Brand: " + m11.brand);
        System.out.println("Type: " + m11.type);
        System.out.println("Dosage: " + m11.dosageMg + "mg");
        System.out.println("Prescription Required: " + m11.isPrescriptionRequired);
        System.out.println("Price: " + m11.price);
        System.out.println("Expiry Date: " + m11.expiryDate);

        Medicine m12 = new Medicine();
        m12.name = "Calcium";
        m12.brand = "Shelcal";
        m12.type = "Tablet";
        m12.dosageMg = 500;
        m12.isPrescriptionRequired = false;
        m12.price = 120;
        m12.expiryDate = "04/2027";
        System.out.println("---------------------------");
        System.out.println("Name: " + m12.name);
        System.out.println("Brand: " + m12.brand);
        System.out.println("Type: " + m12.type);
        System.out.println("Dosage: " + m12.dosageMg + "mg");
        System.out.println("Prescription Required: " + m12.isPrescriptionRequired);
        System.out.println("Price: " + m12.price);
        System.out.println("Expiry Date: " + m12.expiryDate);

        Medicine m13 = new Medicine();
        m13.name = "Insulin";
        m13.brand = "Novorapid";
        m13.type = "Injection";
        m13.dosageMg = 0;
        m13.isPrescriptionRequired = true;
        m13.price = 500;
        m13.expiryDate = "02/2026";
        System.out.println("---------------------------");
        System.out.println("Name: " + m13.name);
        System.out.println("Brand: " + m13.brand);
        System.out.println("Type: " + m13.type);
        System.out.println("Dosage: " + m13.dosageMg + "mg");
        System.out.println("Prescription Required: " + m13.isPrescriptionRequired);
        System.out.println("Price: " + m13.price);
        System.out.println("Expiry Date: " + m13.expiryDate);

        Medicine m14 = new Medicine();
        m14.name = "Aspirin";
        m14.brand = "Ecosprin";
        m14.type = "Tablet";
        m14.dosageMg = 75;
        m14.isPrescriptionRequired = false;
        m14.price = 30;
        m14.expiryDate = "09/2026";
        System.out.println("---------------------------");
        System.out.println("Name: " + m14.name);
        System.out.println("Brand: " + m14.brand);
        System.out.println("Type: " + m14.type);
        System.out.println("Dosage: " + m14.dosageMg + "mg");
        System.out.println("Prescription Required: " + m14.isPrescriptionRequired);
        System.out.println("Price: " + m14.price);
        System.out.println("Expiry Date: " + m14.expiryDate);

        Medicine m15 = new Medicine();
        m15.name = "Ranitidine";
        m15.brand = "Rantac";
        m15.type = "Tablet";
        m15.dosageMg = 150;
        m15.isPrescriptionRequired = true;
        m15.price = 45;
        m15.expiryDate = "08/2026";
        System.out.println("---------------------------");
        System.out.println("Name: " + m15.name);
        System.out.println("Brand: " + m15.brand);
        System.out.println("Type: " + m15.type);
        System.out.println("Dosage: " + m15.dosageMg + "mg");
        System.out.println("Prescription Required: " + m15.isPrescriptionRequired);
        System.out.println("Price: " + m15.price);
        System.out.println("Expiry Date: " + m15.expiryDate);

        Medicine m16 = new Medicine();
        m16.name = "Domperidone";
        m16.brand = "Domstal";
        m16.type = "Tablet";
        m16.dosageMg = 10;
        m16.isPrescriptionRequired = true;
        m16.price = 55;
        m16.expiryDate = "10/2026";
        System.out.println("---------------------------");
        System.out.println("Name: " + m16.name);
        System.out.println("Brand: " + m16.brand);
        System.out.println("Type: " + m16.type);
        System.out.println("Dosage: " + m16.dosageMg + "mg");
        System.out.println("Prescription Required: " + m16.isPrescriptionRequired);
        System.out.println("Price: " + m16.price);
        System.out.println("Expiry Date: " + m16.expiryDate);

        Medicine m17 = new Medicine();
        m17.name = "Loratadine";
        m17.brand = "Lorat";
        m17.type = "Tablet";
        m17.dosageMg = 10;
        m17.isPrescriptionRequired = false;
        m17.price = 25;
        m17.expiryDate = "11/2026";
        System.out.println("---------------------------");
        System.out.println("Name: " + m17.name);
        System.out.println("Brand: " + m17.brand);
        System.out.println("Type: " + m17.type);
        System.out.println("Dosage: " + m17.dosageMg + "mg");
        System.out.println("Prescription Required: " + m17.isPrescriptionRequired);
        System.out.println("Price: " + m17.price);
        System.out.println("Expiry Date: " + m17.expiryDate);

        Medicine m18 = new Medicine();
        m18.name = "Albendazole";
        m18.brand = "Zentel";
        m18.type = "Tablet";
        m18.dosageMg = 400;
        m18.isPrescriptionRequired = false;
        m18.price = 20;
        m18.expiryDate = "05/2027";
        System.out.println("---------------------------");
        System.out.println("Name: " + m18.name);
        System.out.println("Brand: " + m18.brand);
        System.out.println("Type: " + m18.type);
        System.out.println("Dosage: " + m18.dosageMg + "mg");
        System.out.println("Prescription Required: " + m18.isPrescriptionRequired);
        System.out.println("Price: " + m18.price);
        System.out.println("Expiry Date: " + m18.expiryDate);

        Medicine m19 = new Medicine();
        m19.name = "Diclofenac";
        m19.brand = "Voveran";
        m19.type = "Tablet";
        m19.dosageMg = 50;
        m19.isPrescriptionRequired = true;
        m19.price = 60;
        m19.expiryDate = "06/2026";
        System.out.println("---------------------------");
        System.out.println("Name: " + m19.name);
        System.out.println("Brand: " + m19.brand);
        System.out.println("Type: " + m19.type);
        System.out.println("Dosage: " + m19.dosageMg + "mg");
        System.out.println("Prescription Required: " + m19.isPrescriptionRequired);
        System.out.println("Price: " + m19.price);
        System.out.println("Expiry Date: " + m19.expiryDate);

        Medicine m20 = new Medicine();
        m20.name = "Multivitamin";
        m20.brand = "Revital";
        m20.type = "Capsule";
        m20.dosageMg = 0;
        m20.isPrescriptionRequired = false;
        m20.price = 180;
        m20.expiryDate = "12/2027";
        System.out.println("---------------------------");
        System.out.println("Name: " + m20.name);
        System.out.println("Brand: " + m20.brand);
        System.out.println("Type: " + m20.type);
        System.out.println("Dosage: " + m20.dosageMg + "mg");
        System.out.println("Prescription Required: " + m20.isPrescriptionRequired);
        System.out.println("Price: " + m20.price);
        System.out.println("Expiry Date: " + m20.expiryDate);

        Medicine m21 = new Medicine();
        m21.name = "Cough Drops";
        m21.brand = "Digene";
        m21.type = "Syrup";
        m21.dosageMg = 0;
        m21.isPrescriptionRequired = false;
        m21.price = 90;
        m21.expiryDate = "03/2027";
        System.out.println("---------------------------");
        System.out.println("Name: " + m21.name);
        System.out.println("Brand: " + m21.brand);
        System.out.println("Type: " + m21.type);
        System.out.println("Dosage: " + m21.dosageMg + "mg");
        System.out.println("Prescription Required: " + m21.isPrescriptionRequired);
        System.out.println("Price: " + m21.price);
        System.out.println("Expiry Date: " + m21.expiryDate);

        Medicine m22 = new Medicine();
        m22.name = "Amoxiclav";
        m22.brand = "Augmentin";
        m22.type = "Tablet";
        m22.dosageMg = 625;
        m22.isPrescriptionRequired = true;
        m22.price = 200;
        m22.expiryDate = "07/2026";
        System.out.println("---------------------------");
        System.out.println("Name: " + m22.name);
        System.out.println("Brand: " + m22.brand);
        System.out.println("Type: " + m22.type);
        System.out.println("Dosage: " + m22.dosageMg + "mg");
        System.out.println("Prescription Required: " + m22.isPrescriptionRequired);
        System.out.println("Price: " + m22.price);
        System.out.println("Expiry Date: " + m22.expiryDate);

        Medicine m23 = new Medicine();
        m23.name = "Montelukast";
        m23.brand = "Montair";
        m23.type = "Tablet";
        m23.dosageMg = 10;
        m23.isPrescriptionRequired = true;
        m23.price = 120;
        m23.expiryDate = "09/2026";
        System.out.println("---------------------------");
        System.out.println("Name: " + m23.name);
        System.out.println("Brand: " + m23.brand);
        System.out.println("Type: " + m23.type);
        System.out.println("Dosage: " + m23.dosageMg + "mg");
        System.out.println("Prescription Required: " + m23.isPrescriptionRequired);
        System.out.println("Price: " + m23.price);
        System.out.println("Expiry Date: " + m23.expiryDate);

        Medicine m24 = new Medicine();
        m24.name = "Hydroxychloroquine";
        m24.brand = "HCQS";
        m24.type = "Tablet";
        m24.dosageMg = 200;
        m24.isPrescriptionRequired = true;
        m24.price = 150;
        m24.expiryDate = "01/2027";
        System.out.println("---------------------------");
        System.out.println("Name: " + m24.name);
        System.out.println("Brand: " + m24.brand);
        System.out.println("Type: " + m24.type);
        System.out.println("Dosage: " + m24.dosageMg + "mg");
        System.out.println("Prescription Required: " + m24.isPrescriptionRequired);
        System.out.println("Price: " + m24.price);
        System.out.println("Expiry Date: " + m24.expiryDate);

        Medicine m25 = new Medicine();
        m25.name = "Vitamin D";
        m25.brand = "Uprise D3";
        m25.type = "Capsule";
        m25.dosageMg = 60000;
        m25.isPrescriptionRequired = false;
        m25.price = 120;
        m25.expiryDate = "10/2027";
        System.out.println("---------------------------");
        System.out.println("Name: " + m25.name);
        System.out.println("Brand: " + m25.brand);
        System.out.println("Type: " + m25.type);
        System.out.println("Dosage: " + m25.dosageMg + "mg");
        System.out.println("Prescription Required: " + m25.isPrescriptionRequired);
        System.out.println("Price: " + m25.price);
        System.out.println("Expiry Date: " + m25.expiryDate);

        Medicine m26 = new Medicine();
        m26.name = "Antiseptic";
        m26.brand = "Fefol";
        m26.type = "Capsule";
        m26.dosageMg = 150;
        m26.isPrescriptionRequired = false;
        m26.price = 100;
        m26.expiryDate = "08/2027";
        System.out.println("---------------------------");
        System.out.println("Name: " + m26.name);
        System.out.println("Brand: " + m26.brand);
        System.out.println("Type: " + m26.type);
        System.out.println("Dosage: " + m26.dosageMg + "mg");
        System.out.println("Prescription Required: " + m26.isPrescriptionRequired);
        System.out.println("Price: " + m26.price);
        System.out.println("Expiry Date: " + m26.expiryDate);

        Medicine m27 = new Medicine();
        m27.name = "Antibiotic";
        m27.brand = "Ciplox";
        m27.type = "Tablet";
        m27.dosageMg = 500;
        m27.isPrescriptionRequired = true;
        m27.price = 140;
        m27.expiryDate = "06/2026";
        System.out.println("---------------------------");
        System.out.println("Name: " + m27.name);
        System.out.println("Brand: " + m27.brand);
        System.out.println("Type: " + m27.type);
        System.out.println("Dosage: " + m27.dosageMg + "mg");
        System.out.println("Prescription Required: " + m27.isPrescriptionRequired);
        System.out.println("Price: " + m27.price);
        System.out.println("Expiry Date: " + m27.expiryDate);

        Medicine m28 = new Medicine();
        m28.name = "Pain Relief Gel";
        m28.brand = "Volini";
        m28.type = "Gel";
        m28.dosageMg = 0;
        m28.isPrescriptionRequired = false;
        m28.price = 110;
        m28.expiryDate = "12/2026";
        System.out.println("---------------------------");
        System.out.println("Name: " + m28.name);
        System.out.println("Brand: " + m28.brand);
        System.out.println("Type: " + m28.type);
        System.out.println("Dosage: " + m28.dosageMg + "mg");
        System.out.println("Prescription Required: " + m28.isPrescriptionRequired);
        System.out.println("Price: " + m28.price);
        System.out.println("Expiry Date: " + m28.expiryDate);

        Medicine m29 = new Medicine();
        m29.name = "Iron";
        m29.brand = "Dettol";
        m29.type = "Liquid";
        m29.dosageMg = 0;
        m29.isPrescriptionRequired = false;
        m29.price = 150;
        m29.expiryDate = "05/2028";
        System.out.println("---------------------------");
        System.out.println("Name: " + m29.name);
        System.out.println("Brand: " + m29.brand);
        System.out.println("Type: " + m29.type);
        System.out.println("Dosage: " + m29.dosageMg + "mg");
        System.out.println("Prescription Required: " + m29.isPrescriptionRequired);
        System.out.println("Price: " + m29.price);
        System.out.println("Expiry Date: " + m29.expiryDate);

        Medicine m30 = new Medicine();
        m30.name = "Antacid";
        m30.brand = "Vicks";
        m30.type = "Lozenge";
        m30.dosageMg = 0;
        m30.isPrescriptionRequired = false;
        m30.price = 20;
        m30.expiryDate = "09/2027";
        System.out.println("---------------------------");
        System.out.println("Name: " + m30.name);
        System.out.println("Brand: " + m30.brand);
        System.out.println("Type: " + m30.type);
        System.out.println("Dosage: " + m30.dosageMg + "mg");
        System.out.println("Prescription Required: " + m30.isPrescriptionRequired);
        System.out.println("Price: " + m30.price);
        System.out.println("Expiry Date: " + m30.expiryDate);

    }
}