class SwitchBoxExecutor {

    public static void main(String[] args) {

        System.out.println("---------------------------");

        SwitchBox sb1 = new SwitchBox();

        sb1.brand = "Anchor";
        sb1.numberOfSwitches = 4;
        sb1.material = "Plastic";
        sb1.color = "White";
        sb1.hasIndicator = true;
        sb1.isModular = true;
        sb1.price = 250;

        System.out.println("Brand: " + sb1.brand);
        System.out.println("Number of Switches: " + sb1.numberOfSwitches);
        System.out.println("Material: " + sb1.material);
        System.out.println("Color: " + sb1.color);
        System.out.println("Has Indicator: " + sb1.hasIndicator);
        System.out.println("Is Modular: " + sb1.isModular);
        System.out.println("Price: " + sb1.price);


        System.out.println("---------------------------");

        SwitchBox sb2 = new SwitchBox();

        sb2.brand = "Havells";
        sb2.numberOfSwitches = 6;
        sb2.material = "Polycarbonate";
        sb2.color = "Ivory";
        sb2.hasIndicator = true;
        sb2.isModular = true;
        sb2.price = 450;

        System.out.println("Brand: " + sb2.brand);
        System.out.println("Number of Switches: " + sb2.numberOfSwitches);
        System.out.println("Material: " + sb2.material);
        System.out.println("Color: " + sb2.color);
        System.out.println("Has Indicator: " + sb2.hasIndicator);
        System.out.println("Is Modular: " + sb2.isModular);
        System.out.println("Price: " + sb2.price);

        SwitchBox sb3 = new SwitchBox();
        sb3.brand = "GM";
        sb3.numberOfSwitches = 5;
        sb3.material = "Plastic";
        sb3.color = "White";
        sb3.hasIndicator = true;
        sb3.isModular = true;
        sb3.price = 300;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb3.brand);
        System.out.println("Number of Switches: " + sb3.numberOfSwitches);
        System.out.println("Material: " + sb3.material);
        System.out.println("Color: " + sb3.color);
        System.out.println("Has Indicator: " + sb3.hasIndicator);
        System.out.println("Is Modular: " + sb3.isModular);
        System.out.println("Price: " + sb3.price);

        SwitchBox sb4 = new SwitchBox();
        sb4.brand = "Legrand";
        sb4.numberOfSwitches = 8;
        sb4.material = "Polycarbonate";
        sb4.color = "White";
        sb4.hasIndicator = true;
        sb4.isModular = true;
        sb4.price = 800;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb4.brand);
        System.out.println("Number of Switches: " + sb4.numberOfSwitches);
        System.out.println("Material: " + sb4.material);
        System.out.println("Color: " + sb4.color);
        System.out.println("Has Indicator: " + sb4.hasIndicator);
        System.out.println("Is Modular: " + sb4.isModular);
        System.out.println("Price: " + sb4.price);

        SwitchBox sb5 = new SwitchBox();
        sb5.brand = "Orient";
        sb5.numberOfSwitches = 3;
        sb5.material = "Plastic";
        sb5.color = "Beige";
        sb5.hasIndicator = false;
        sb5.isModular = false;
        sb5.price = 180;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb5.brand);
        System.out.println("Number of Switches: " + sb5.numberOfSwitches);
        System.out.println("Material: " + sb5.material);
        System.out.println("Color: " + sb5.color);
        System.out.println("Has Indicator: " + sb5.hasIndicator);
        System.out.println("Is Modular: " + sb5.isModular);
        System.out.println("Price: " + sb5.price);

        SwitchBox sb6 = new SwitchBox();
        sb6.brand = "Philips";
        sb6.numberOfSwitches = 6;
        sb6.material = "Polycarbonate";
        sb6.color = "White";
        sb6.hasIndicator = true;
        sb6.isModular = true;
        sb6.price = 600;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb6.brand);
        System.out.println("Number of Switches: " + sb6.numberOfSwitches);
        System.out.println("Material: " + sb6.material);
        System.out.println("Color: " + sb6.color);
        System.out.println("Has Indicator: " + sb6.hasIndicator);
        System.out.println("Is Modular: " + sb6.isModular);
        System.out.println("Price: " + sb6.price);

        SwitchBox sb7 = new SwitchBox();
        sb7.brand = "Syska";
        sb7.numberOfSwitches = 4;
        sb7.material = "Plastic";
        sb7.color = "Grey";
        sb7.hasIndicator = false;
        sb7.isModular = true;
        sb7.price = 220;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb7.brand);
        System.out.println("Number of Switches: " + sb7.numberOfSwitches);
        System.out.println("Material: " + sb7.material);
        System.out.println("Color: " + sb7.color);
        System.out.println("Has Indicator: " + sb7.hasIndicator);
        System.out.println("Is Modular: " + sb7.isModular);
        System.out.println("Price: " + sb7.price);

        SwitchBox sb8 = new SwitchBox();
        sb8.brand = "Wipro";
        sb8.numberOfSwitches = 5;
        sb8.material = "Polycarbonate";
        sb8.color = "White";
        sb8.hasIndicator = true;
        sb8.isModular = true;
        sb8.price = 350;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb8.brand);
        System.out.println("Number of Switches: " + sb8.numberOfSwitches);
        System.out.println("Material: " + sb8.material);
        System.out.println("Color: " + sb8.color);
        System.out.println("Has Indicator: " + sb8.hasIndicator);
        System.out.println("Is Modular: " + sb8.isModular);
        System.out.println("Price: " + sb8.price);

        SwitchBox sb9 = new SwitchBox();
        sb9.brand = "Bajaj";
        sb9.numberOfSwitches = 6;
        sb9.material = "Plastic";
        sb9.color = "Ivory";
        sb9.hasIndicator = true;
        sb9.isModular = false;
        sb9.price = 300;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb9.brand);
        System.out.println("Number of Switches: " + sb9.numberOfSwitches);
        System.out.println("Material: " + sb9.material);
        System.out.println("Color: " + sb9.color);
        System.out.println("Has Indicator: " + sb9.hasIndicator);
        System.out.println("Is Modular: " + sb9.isModular);
        System.out.println("Price: " + sb9.price);

        SwitchBox sb10 = new SwitchBox();
        sb10.brand = "Crompton";
        sb10.numberOfSwitches = 4;
        sb10.material = "Plastic";
        sb10.color = "White";
        sb10.hasIndicator = true;
        sb10.isModular = true;
        sb10.price = 280;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb10.brand);
        System.out.println("Number of Switches: " + sb10.numberOfSwitches);
        System.out.println("Material: " + sb10.material);
        System.out.println("Color: " + sb10.color);
        System.out.println("Has Indicator: " + sb10.hasIndicator);
        System.out.println("Is Modular: " + sb10.isModular);
        System.out.println("Price: " + sb10.price);

        SwitchBox sb11 = new SwitchBox();
        sb11.brand = "Panasonic";
        sb11.numberOfSwitches = 8;
        sb11.material = "Polycarbonate";
        sb11.color = "White";
        sb11.hasIndicator = true;
        sb11.isModular = true;
        sb11.price = 900;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb11.brand);
        System.out.println("Number of Switches: " + sb11.numberOfSwitches);
        System.out.println("Material: " + sb11.material);
        System.out.println("Color: " + sb11.color);
        System.out.println("Has Indicator: " + sb11.hasIndicator);
        System.out.println("Is Modular: " + sb11.isModular);
        System.out.println("Price: " + sb11.price);

        SwitchBox sb12 = new SwitchBox();
        sb12.brand = "Finolex";
        sb12.numberOfSwitches = 5;
        sb12.material = "Plastic";
        sb12.color = "Beige";
        sb12.hasIndicator = false;
        sb12.isModular = false;
        sb12.price = 200;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb12.brand);
        System.out.println("Number of Switches: " + sb12.numberOfSwitches);
        System.out.println("Material: " + sb12.material);
        System.out.println("Color: " + sb12.color);
        System.out.println("Has Indicator: " + sb12.hasIndicator);
        System.out.println("Is Modular: " + sb12.isModular);
        System.out.println("Price: " + sb12.price);

        SwitchBox sb13 = new SwitchBox();
        sb13.brand = "RR Kabel";
        sb13.numberOfSwitches = 6;
        sb13.material = "Polycarbonate";
        sb13.color = "White";
        sb13.hasIndicator = true;
        sb13.isModular = true;
        sb13.price = 500;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb13.brand);
        System.out.println("Number of Switches: " + sb13.numberOfSwitches);
        System.out.println("Material: " + sb13.material);
        System.out.println("Color: " + sb13.color);
        System.out.println("Has Indicator: " + sb13.hasIndicator);
        System.out.println("Is Modular: " + sb13.isModular);
        System.out.println("Price: " + sb13.price);

        SwitchBox sb14 = new SwitchBox();
        sb14.brand = "Polycab";
        sb14.numberOfSwitches = 7;
        sb14.material = "Polycarbonate";
        sb14.color = "White";
        sb14.hasIndicator = true;
        sb14.isModular = true;
        sb14.price = 650;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb14.brand);
        System.out.println("Number of Switches: " + sb14.numberOfSwitches);
        System.out.println("Material: " + sb14.material);
        System.out.println("Color: " + sb14.color);
        System.out.println("Has Indicator: " + sb14.hasIndicator);
        System.out.println("Is Modular: " + sb14.isModular);
        System.out.println("Price: " + sb14.price);

        SwitchBox sb15 = new SwitchBox();
        sb15.brand = "Goldmedal";
        sb15.numberOfSwitches = 4;
        sb15.material = "Plastic";
        sb15.color = "White";
        sb15.hasIndicator = true;
        sb15.isModular = true;
        sb15.price = 300;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb15.brand);
        System.out.println("Number of Switches: " + sb15.numberOfSwitches);
        System.out.println("Material: " + sb15.material);
        System.out.println("Color: " + sb15.color);
        System.out.println("Has Indicator: " + sb15.hasIndicator);
        System.out.println("Is Modular: " + sb15.isModular);
        System.out.println("Price: " + sb15.price);

        SwitchBox sb16 = new SwitchBox();
        sb16.brand = "Simon";
        sb16.numberOfSwitches = 8;
        sb16.material = "Polycarbonate";
        sb16.color = "White";
        sb16.hasIndicator = true;
        sb16.isModular = true;
        sb16.price = 950;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb16.brand);
        System.out.println("Number of Switches: " + sb16.numberOfSwitches);
        System.out.println("Material: " + sb16.material);
        System.out.println("Color: " + sb16.color);
        System.out.println("Has Indicator: " + sb16.hasIndicator);
        System.out.println("Is Modular: " + sb16.isModular);
        System.out.println("Price: " + sb16.price);

        SwitchBox sb17 = new SwitchBox();
        sb17.brand = "V-Guard";
        sb17.numberOfSwitches = 5;
        sb17.material = "Plastic";
        sb17.color = "Grey";
        sb17.hasIndicator = false;
        sb17.isModular = true;
        sb17.price = 270;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb17.brand);
        System.out.println("Number of Switches: " + sb17.numberOfSwitches);
        System.out.println("Material: " + sb17.material);
        System.out.println("Color: " + sb17.color);
        System.out.println("Has Indicator: " + sb17.hasIndicator);
        System.out.println("Is Modular: " + sb17.isModular);
        System.out.println("Price: " + sb17.price);

        SwitchBox sb18 = new SwitchBox();
        sb18.brand = "Usha";
        sb18.numberOfSwitches = 6;
        sb18.material = "Plastic";
        sb18.color = "White";
        sb18.hasIndicator = true;
        sb18.isModular = false;
        sb18.price = 320;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb18.brand);
        System.out.println("Number of Switches: " + sb18.numberOfSwitches);
        System.out.println("Material: " + sb18.material);
        System.out.println("Color: " + sb18.color);
        System.out.println("Has Indicator: " + sb18.hasIndicator);
        System.out.println("Is Modular: " + sb18.isModular);
        System.out.println("Price: " + sb18.price);

        SwitchBox sb19 = new SwitchBox();
        sb19.brand = "Orient Electric";
        sb19.numberOfSwitches = 4;
        sb19.material = "Plastic";
        sb19.color = "Ivory";
        sb19.hasIndicator = true;
        sb19.isModular = false;
        sb19.price = 260;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb19.brand);
        System.out.println("Number of Switches: " + sb19.numberOfSwitches);
        System.out.println("Material: " + sb19.material);
        System.out.println("Color: " + sb19.color);
        System.out.println("Has Indicator: " + sb19.hasIndicator);
        System.out.println("Is Modular: " + sb19.isModular);
        System.out.println("Price: " + sb19.price);

        SwitchBox sb20 = new SwitchBox();
        sb20.brand = "Anchor Roma";
        sb20.numberOfSwitches = 7;
        sb20.material = "Polycarbonate";
        sb20.color = "White";
        sb20.hasIndicator = true;
        sb20.isModular = true;
        sb20.price = 700;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb20.brand);
        System.out.println("Number of Switches: " + sb20.numberOfSwitches);
        System.out.println("Material: " + sb20.material);
        System.out.println("Color: " + sb20.color);
        System.out.println("Has Indicator: " + sb20.hasIndicator);
        System.out.println("Is Modular: " + sb20.isModular);
        System.out.println("Price: " + sb20.price);

        SwitchBox sb21 = new SwitchBox();
        sb21.brand = "GM Modular";
        sb21.numberOfSwitches = 5;
        sb21.material = "Polycarbonate";
        sb21.color = "White";
        sb21.hasIndicator = true;
        sb21.isModular = true;
        sb21.price = 420;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb21.brand);
        System.out.println("Number of Switches: " + sb21.numberOfSwitches);
        System.out.println("Material: " + sb21.material);
        System.out.println("Color: " + sb21.color);
        System.out.println("Has Indicator: " + sb21.hasIndicator);
        System.out.println("Is Modular: " + sb21.isModular);
        System.out.println("Price: " + sb21.price);

        SwitchBox sb22 = new SwitchBox();
        sb22.brand = "Legrand Myrius";
        sb22.numberOfSwitches = 8;
        sb22.material = "Polycarbonate";
        sb22.color = "White";
        sb22.hasIndicator = true;
        sb22.isModular = true;
        sb22.price = 1000;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb22.brand);
        System.out.println("Number of Switches: " + sb22.numberOfSwitches);
        System.out.println("Material: " + sb22.material);
        System.out.println("Color: " + sb22.color);
        System.out.println("Has Indicator: " + sb22.hasIndicator);
        System.out.println("Is Modular: " + sb22.isModular);
        System.out.println("Price: " + sb22.price);

        SwitchBox sb23 = new SwitchBox();
        sb23.brand = "Havells Fabio";
        sb23.numberOfSwitches = 6;
        sb23.material = "Polycarbonate";
        sb23.color = "Ivory";
        sb23.hasIndicator = true;
        sb23.isModular = true;
        sb23.price = 550;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb23.brand);
        System.out.println("Number of Switches: " + sb23.numberOfSwitches);
        System.out.println("Material: " + sb23.material);
        System.out.println("Color: " + sb23.color);
        System.out.println("Has Indicator: " + sb23.hasIndicator);
        System.out.println("Is Modular: " + sb23.isModular);
        System.out.println("Price: " + sb23.price);

        SwitchBox sb24 = new SwitchBox();
        sb24.brand = "Wipro NorthWest";
        sb24.numberOfSwitches = 5;
        sb24.material = "Polycarbonate";
        sb24.color = "White";
        sb24.hasIndicator = true;
        sb24.isModular = true;
        sb24.price = 400;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb24.brand);
        System.out.println("Number of Switches: " + sb24.numberOfSwitches);
        System.out.println("Material: " + sb24.material);
        System.out.println("Color: " + sb24.color);
        System.out.println("Has Indicator: " + sb24.hasIndicator);
        System.out.println("Is Modular: " + sb24.isModular);
        System.out.println("Price: " + sb24.price);

        SwitchBox sb25 = new SwitchBox();
        sb25.brand = "Bajaj Ivora";
        sb25.numberOfSwitches = 4;
        sb25.material = "Plastic";
        sb25.color = "Ivory";
        sb25.hasIndicator = false;
        sb25.isModular = false;
        sb25.price = 230;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb25.brand);
        System.out.println("Number of Switches: " + sb25.numberOfSwitches);
        System.out.println("Material: " + sb25.material);
        System.out.println("Color: " + sb25.color);
        System.out.println("Has Indicator: " + sb25.hasIndicator);
        System.out.println("Is Modular: " + sb25.isModular);
        System.out.println("Price: " + sb25.price);

        SwitchBox sb26 = new SwitchBox();
        sb26.brand = "Crompton Mini";
        sb26.numberOfSwitches = 3;
        sb26.material = "Plastic";
        sb26.color = "White";
        sb26.hasIndicator = false;
        sb26.isModular = false;
        sb26.price = 150;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb26.brand);
        System.out.println("Number of Switches: " + sb26.numberOfSwitches);
        System.out.println("Material: " + sb26.material);
        System.out.println("Color: " + sb26.color);
        System.out.println("Has Indicator: " + sb26.hasIndicator);
        System.out.println("Is Modular: " + sb26.isModular);
        System.out.println("Price: " + sb26.price);

        SwitchBox sb27 = new SwitchBox();
        sb27.brand = "Syska Pro";
        sb27.numberOfSwitches = 6;
        sb27.material = "Polycarbonate";
        sb27.color = "Grey";
        sb27.hasIndicator = true;
        sb27.isModular = true;
        sb27.price = 500;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb27.brand);
        System.out.println("Number of Switches: " + sb27.numberOfSwitches);
        System.out.println("Material: " + sb27.material);
        System.out.println("Color: " + sb27.color);
        System.out.println("Has Indicator: " + sb27.hasIndicator);
        System.out.println("Is Modular: " + sb27.isModular);
        System.out.println("Price: " + sb27.price);

        SwitchBox sb28 = new SwitchBox();
        sb28.brand = "Philips Core";
        sb28.numberOfSwitches = 7;
        sb28.material = "Polycarbonate";
        sb28.color = "White";
        sb28.hasIndicator = true;
        sb28.isModular = true;
        sb28.price = 750;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb28.brand);
        System.out.println("Number of Switches: " + sb28.numberOfSwitches);
        System.out.println("Material: " + sb28.material);
        System.out.println("Color: " + sb28.color);
        System.out.println("Has Indicator: " + sb28.hasIndicator);
        System.out.println("Is Modular: " + sb28.isModular);
        System.out.println("Price: " + sb28.price);

        SwitchBox sb29 = new SwitchBox();
        sb29.brand = "Polycab Smart";
        sb29.numberOfSwitches = 5;
        sb29.material = "Polycarbonate";
        sb29.color = "White";
        sb29.hasIndicator = true;
        sb29.isModular = true;
        sb29.price = 480;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb29.brand);
        System.out.println("Number of Switches: " + sb29.numberOfSwitches);
        System.out.println("Material: " + sb29.material);
        System.out.println("Color: " + sb29.color);
        System.out.println("Has Indicator: " + sb29.hasIndicator);
        System.out.println("Is Modular: " + sb29.isModular);
        System.out.println("Price: " + sb29.price);

        SwitchBox sb30 = new SwitchBox();
        sb30.brand = "Goldmedal Curve";
        sb30.numberOfSwitches = 8;
        sb30.material = "Polycarbonate";
        sb30.color = "White";
        sb30.hasIndicator = true;
        sb30.isModular = true;
        sb30.price = 900;
        System.out.println("---------------------------");
        System.out.println("Brand: " + sb30.brand);
        System.out.println("Number of Switches: " + sb30.numberOfSwitches);
        System.out.println("Material: " + sb30.material);
        System.out.println("Color: " + sb30.color);
        System.out.println("Has Indicator: " + sb30.hasIndicator);
        System.out.println("Is Modular: " + sb30.isModular);
        System.out.println("Price: " + sb30.price);
    }
}
